### PR TITLE
Second attempt at fixing the broken package

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by jochym** [comment]
Maybe we should ask authors for assistance?

**Comment by Cadair** [comment]
We should do that. However, given the fact that the pypi tarball seems perfectly OK I have to assume this is an error in the conda process somewhere.

**Comment by jochym** [comment]
You may be right @Cadair but the package has non-trivial structure and we may miss something non-standard they do in the build. I'll contact the authors.

**Comment by DRMacIver** [comment]
>  @Cadair but the package has non-trivial structure 

BTW could you clarify what's non-trivial about the structure that's giving you trouble? I know the testing setup is weird, but the actually packaged bits should be entirely standard.

**Comment by jochym** [comment]
This was finally fixed in https://github.com/conda-forge/hypothesis-feedstock/pull/19 - I am closing this now.

**Pull request closed without merging**
