### PR TITLE
Py37

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by jochym** [comment]
Why we are dropping the tests? We spotted multiple problematic corner cases  and errors thanks to these tests. And this is a testing framework - it should better be well-tested...

**Comment by ocefpaf** [comment]
> Why we are dropping the tests?

Heavy testing like that should be done upstream. Getting the source via `git` and running all the battery of tests is too costly for the CIs.

> We spotted multiple problematic corner cases and errors thanks to these tests. And this is a testing framework - it should better be well-tested...

I wonder if that was due to packaging issues or real failures b/c we do expect the package to be tested upstream before a release.

With that said all the tests were passing when I sent this PR with the exception of one failure due to a false positive on a pandas warning. That is one reason why heavy testing here can be problematic, it can delay the publication of a fully functional package.

With that said. I'm not against good testing practices. I just don't want an unnecessary package maintenance and CI burden.

**Comment by jochym** [comment]
You are probably right. This is costly. In this case upstream has a full set of tests and CI - but still some bugs slipped through. I am just afraid we will pack up a faulty package and people will count on it for their own testing (e.g. my personal packages do).

**Comment by ocefpaf** [comment]
> but still some bugs slipped through

I really think those were packaging issue :-/

>  I am just afraid we will pack up a faulty package and people will count on it for their own testing (e.g. my personal packages do).

I also use it on production every day, that is why I want a faster release cycle.

Let's merge this one, if it turns out I break it we re-instate the tests ASAP. OK?

**Pull request merged**
