### PR TITLE
Update attrs dependency

### PR DESCRIPTION
**Pull request by kkraus14**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

attrs dependency referenced here: https://hypothesis.readthedocs.io/en/latest/changes.html#v4-38-2

### CODE REVIEW

**Comment by kkraus14** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
@kkraus14 , could you please try re-rendering locally and share any traceback you see?

This should involve installing `conda-smithy` in your `base` environment and running `conda smithy rerender -c auto` on your branch.

**Comment by kkraus14** [comment]
Done!

**Comment by jakirkham** [comment]
Thanks Keith. Glad that worked. Looks like this is an issue with the bot then. Will look into it.

**Comment by jakirkham** [comment]
@conda-forge/hypothesis, could you please take a look?

@kkraus14, does this mean we should pull the packages that have this dependency incorrect?

**Comment by kkraus14** [comment]
> @conda-forge/hypothesis, could you please take a look?
> 
> @kkraus14, does this mean we should pull the packages that have this dependency incorrect?

It's broken with `attrs < 19.2.0`, but I'm unsure of the policy as to when conda-forge pulls packages or not.

**Comment by jakirkham** [comment]
Yeah this dependency change occurred in the [4.38.2 release]( https://github.com/HypothesisWorks/hypothesis/commit/8ba79a08ab4e471ad84a78e6d6a520ab946fa037 ), which should have been added to PR ( https://github.com/conda-forge/hypothesis-feedstock/pull/332 ) as part of the update, but was missed. Given this it makes sense to pull the release, will go ahead and do that now while we wait for a review.

**Comment by jakirkham** [comment]
Ok have pulled those packages. Please recheck that I got them all, @kkraus14. May take some time to propagate to the CDN. Hopefully this unblocks you 🙂

**Comment by kkraus14** [comment]
@conda-forge/hypothesis Any chance someone could spare some time to review this?

**Pull request merged**
